### ISSUE TITLE
Suggestion to rename types

### ISSUE THREAD

**Issue by michal-minich** [adamhaile/S-array#10]
To match typescript names (and obvious usage):
```
SArray -> ReadonlySArray
SDataArray -> SArray
```
This looks like breaking changes. So it will probably not happen like this. But the names are bit confusing.

**Comment by adamhaile** [comment]
Thanks for the feedback.  The names here are designed to be consistent with the naming conventions in the S docs and the larger synchronous programming literature, where `signal` means a value that may change over time, while `data signal` means that the signal also accepts new values (aka is writeable).

**Comment by michal-minich** [comment]
OK, no prob. thanks for explanation.
